### PR TITLE
Added support for float and int types as well as color for animator's valueFrom/valueTo.

### PR DESCRIPTION
**Pull request by twyatt**
Fix for issue #16.

### CODE REVIEW

**Comment by ghost** [comment]
I test it with:
android:valueFrom="#444444"
android:valueTo="#F44336" 
Animation changed colour incorrect
Where is the problem? Thanks for help!
P/s: Why VectorDrawable draw on Kitkat, it is not smooth(AntiAlias) as Lolipop?

**Comment by twyatt** [comment]
This update was intended to address integer/float values as is used for properties such as strokeAlpha or fillAlpha. I was planning on diving into the color values soon.

**Comment by ghost** [comment]
Thanks

**Comment by twyatt** [comment]
@ladhot This pull request now includes support for animating the vector path's color (e.g. `fillColor`) in the `valueFrom` or `valueTo`. A value is considered a color if it begins with a `#` character (e.g. `#ff0000` for red).

**Comment by ghost** [comment]
Great, thank you!

**Comment by RustamG** [comment]
@wnafee Can you share this version to the maven central, please?

**Comment by Twinkle942910** [comment]
fillColor doesn't work(

**Comment by Twinkle942910** [comment]
@twyatt Doesn't work( When i use fillColor animation, I have errors.

**Comment by twyatt** [comment]
@Twinkle942910 Could you paste your error (i.e. stacktrace) and assets that are causing you problems?

**Comment by Twinkle942910** [comment]
@twyatt Here's my error list

# LogCat <tag>

```
01-24 16:58:20.536 1654-1654/? E/AndroidRuntime: FATAL EXCEPTION: main
01-24 16:58:20.536 1654-1654/? E/AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.twinkle.attachsvg/com.twinkle.attachsvg.activity.MainActivity}: android.content.res.Resources$NotFoundException: File res/drawable/circle_avd.xml from drawable resource ID #0x7f020045
01-24 16:58:20.536 1654-1654/? E/AndroidRuntime:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2059)
01-24 16:58:20.536 1654-1654/? E/AndroidRuntime:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2084)
01-24 16:58:20.536 1654-1654/? E/AndroidRuntime:     at android.app.ActivityThread.access$600(ActivityThread.java:130)
01-24 16:58:20.536 1654-1654/? E/AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1195)
01-24 16:58:20.536 1654-1654/? E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:99)
01-24 16:58:20.536 1654-1654/? E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:137)
01-24 16:58:20.536 1654-1654/? E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:4745)
01-24 16:58:20.536 1654-1654/? E/AndroidRuntime:     at java.lang.reflect.Method.invokeNative(Native Method)
01-24 16:58:20.536 1654-1654/? E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:511)
01-24 16:58:20.536 1654-1654/? E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
01-24 16:58:20.536 1654-1654/? E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
01-24 16:58:20.536 1654-1654/? E/AndroidRuntime:     at dalvik.system.NativeStart.main(Native Method)
01-24 16:58:20.536 1654-1654/? E/AndroidRuntime:  Caused by: android.content.res.Resources$NotFoundException: File res/drawable/circle_avd.xml from drawable resource ID #0x7f020045
01-24 16:58:20.536 1654-1654/? E/AndroidRuntime:     at android.content.res.Resources.loadDrawable(Resources.java:1918)
01-24 16:58:20.536 1654-1654/? E/AndroidRuntime:     at android.content.res.Resources.getDrawable(Resources.java:659)
01-24 16:58:20.536 1654-1654/? E/AndroidRuntime:     at com.wnafee.vector.compat.ResourcesCompat.getDrawable(ResourcesCompat.java:34)
01-24 16:58:20.536 1654-1654/? E/AndroidRuntime:     at com.twinkle.attachsvg.activity.MainActivity.onCreate(MainActivity.java:33)
01-24 16:58:20.536 1654-1654/? E/AndroidRuntime:     at android.app.Activity.performCreate(Activity.java:5008)
01-24 16:58:20.536 1654-1654/? E/AndroidRuntime:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1079)
01-24 16:58:20.536 1654-1654/? E/AndroidRuntime:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2023)
01-24 16:58:20.536 1654-1654/? E/AndroidRuntime:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2084) 
01-24 16:58:20.536 1654-1654/? E/AndroidRuntime:     at android.app.ActivityThread.access$600(ActivityThread.java:130) 
01-24 16:58:20.536 1654-1654/? E/AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1195) 
01-24 16:58:20.536 1654-1654/? E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:99) 
01-24 16:58:20.536 1654-1654/? E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:137) 
01-24 16:58:20.536 1654-1654/? E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:4745) 
01-24 16:58:20.536 1654-1654/? E/AndroidRuntime:     at java.lang.reflect.Method.invokeNative(Native Method) 
01-24 16:58:20.536 1654-1654/? E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:511) 
01-24 16:58:20.536 1654-1654/? E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786) 
01-24 16:58:20.536 1654-1654/? E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553) 
01-24 16:58:20.536 1654-1654/? E/AndroidRuntime:     at dalvik.system.NativeStart.main(Native Method) 
01-24 16:58:20.536 1654-1654/? E/AndroidRuntime:  Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #2: invalid drawable tag animated-vector
01-24 16:58:20.536 1654-1654/? E/AndroidRuntime:     at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:877)
01-24 16:58:20.536 1654-1654/? E/AndroidRuntime:     at android.graphics.drawable.Drawable.createFromXml(Drawable.java:818)
01-24 16:58:20.536 1654-1654/? E/AndroidRuntime:     at android.content.res.Resources.loadDrawable(Resources.java:1915)
01-24 16:58:20.536 1654-1654/? E/AndroidRuntime:     at android.content.res.Resources.getDrawable(Resources.java:659) 
01-24 16:58:20.536 1654-1654/? E/AndroidRuntime:     at com.wnafee.vector.compat.ResourcesCompat.getDrawable(ResourcesCompat.java:34) 
01-24 16:58:20.536 1654-1654/? E/AndroidRuntime:     at com.twinkle.attachsvg.activity.MainActivity.onCreate(MainActivity.java:33) 
01-24 16:58:20.536 1654-1654/? E/AndroidRuntime:     at android.app.Activity.performCreate(Activity.java:5008) 
01-24 16:58:20.536 1654-1654/? E/AndroidRuntime:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1079) 
01-24 16:58:20.536 1654-1654/? E/AndroidRuntime:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2023) 
01-24 16:58:20.536 1654-1654/? E/AndroidRuntime:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2084) 
01-24 16:58:20.536 1654-1654/? E/AndroidRuntime:     at android.app.ActivityThread.access$600(ActivityThread.java:130) 
01-24 16:58:20.536 1654-1654/? E/AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1195) 
01-24 16:58:20.536 1654-1654/? E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:99) 
01-24 16:58:20.536 1654-1654/? E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:137) 
01-24 16:58:20.536 1654-1654/? E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:4745) 
01-24 16:58:20.536 1654-1654/? E/AndroidRuntime:     at java.lang.reflect.Method.invokeNative(Native Method) 
01-24 16:58:20.536 1654-1654/? E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:511) 
01-24 16:58:20.536 1654-1654/? E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786) 
01-24 16:58:20.536 1654-1654/? E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553) 
01-24 16:58:20.536 1654-1654/? E/AndroidRuntime:     at dalvik.system.NativeStart.main(Native Method) 
```

# drawable/circle_vector.xml <tag>

```
<?xml version="1.0" encoding="utf-8"?>
<vector
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"

    android:viewportWidth="468.4"
    android:viewportHeight="434.7"

    android:width="468.4dp"
    android:height="434.7dp"

    app:vc_viewportHeight="434.7"
    app:vc_viewportWidth="468.4"
    >



    <path
        android:name="font"

        android:pathData="M422 214.2A192.5 192.5 0 0 1 229.5 406.7 192.5 192.5 0 0 1 37 214.2 192.5 192.5 0 0 1 229.5 21.699997 192.5 192.5 0 0 1 422 214.2Z"
        app:vc_pathData="M422 214.2A192.5 192.5 0 0 1 229.5 406.7 192.5 192.5 0 0 1 37 214.2 192.5 192.5 0 0 1 229.5 21.699997 192.5 192.5 0 0 1 422 214.2Z"
        android:fillColor="#76cbc6"
        app:vc_fillColor="#76cbc6">

    </path>

    <path android:name="square"

        android:fillColor="@color/color_from"
        app:vc_fillColor="@color/color_from"
        android:pathData="@string/square_from"
        app:vc_pathData="@string/square_from" />

    <group
        android:name="rotationGroup"
        android:pivotX="360.0"
        android:pivotY="0"
        android:rotation="45.0" >
    <path
        android:name="dot"

        android:fillColor="#FFFFFF"
        app:vc_fillColor="#FFFFFF"
        android:pathData="M295.161,129.438c-6.668,0-12.074-5.407-12.074-12.079c0-6.673,5.406-12.08,12.074-12.08c6.675,0,12.079,5.409,12.079,12.08C307.24,124.03,301.834,129.438,295.161,129.438"
        app:vc_pathData="M295.161,129.438c-6.668,0-12.074-5.407-12.074-12.079c0-6.673,5.406-12.08,12.074-12.08c6.675,0,12.079,5.409,12.079,12.08C307.24,124.03,301.834,129.438,295.161,129.438"/>
    </group>
</vector>
```

# drawable/circle_avd.xml <tag>

```
<?xml version="1.0" encoding="utf-8"?>
<animated-vector
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:drawable="@drawable/circle_vector">

    <target
        android:animation="@anim/circle_anim"
        android:name="rotationGroup"/>

    <target
        android:animation="@anim/square_to_triangle"
        android:name="square"/>

     <target
        android:animation="@anim/color_change"
        android:name="square"/>
</animated-vector>

anim/circle_anim.xml

<?xml version="1.0" encoding="utf-8"?>
<set xmlns:android="http://schemas.android.com/apk/res/android">


    <objectAnimator
        android:duration="3000"
        android:propertyName="rotation"
        android:valueFrom="0"
        android:valueTo="360"
        android:repeatMode="reverse"
        android:repeatCount="infinite"
        android:interpolator="@android:interpolator/accelerate_decelerate"/>

</set>


# anim/square_to_triangle.xml <tag>

<?xml version="1.0" encoding="utf-8"?>
<set xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto">

    <objectAnimator

        android:propertyName="pathData"
        android:valueFrom="@string/square_from"
        android:valueTo="@string/square_to"
        android:valueType="pathType"
        app:vc_valueType="pathType"
        android:duration="1000"

        android:repeatMode="reverse"
        android:repeatCount="infinite"

        android:interpolator="@android:interpolator/decelerate_cubic"/>

</set>
```

# anim/color_cahnge.xml (The ploblem is here. I think) <tag>

```
<?xml version="1.0" encoding="utf-8"?>
<set xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto">

    <objectAnimator
        android:propertyName="fillColor"
        android:valueFrom="@color/color_from"
        android:valueTo="@color/color_to"

        android:valueType="intType"

        android:duration="1000"

        android:repeatCount="infinite"
        android:repeatMode="reverse"

        android:interpolator="@android:interpolator/decelerate_cubic" />

</set>
```

# And MainActivity <tag>

```
package com.twinkle.attachsvg.activity;

import android.app.Activity;
import android.graphics.drawable.Animatable;
import android.graphics.drawable.Drawable;
import android.os.Build;
import android.os.Bundle;
import android.view.View;
import android.widget.Button;
import android.widget.ImageView;

import com.twinkle.attachsvg.CanvasView;
import com.twinkle.attachsvg.R;
import com.wnafee.vector.compat.ResourcesCompat;

public class MainActivity extends Activity {

    private Drawable circle;
    private CanvasView canvas;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        final ImageView anim = (ImageView) findViewById(R.id.anuma);
        Drawable droid = ResourcesCompat.getDrawable(this, R.drawable.circle_avd);
            anim.setBackground(droid);
        Button btn = (Button) findViewById(R.id.butt1);

        btn.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                ((Animatable) anim.getBackground()).start();
            }
        });


    }
}
```

Sorry for bad formating( 
Thanks for help

**Comment by Twinkle942910** [comment]
@twyatt And that works without 

```
 <target
    android:animation="@anim/color_change"
    android:name="square"/>
```

in drawable/circle_avd.xml <tag>

**Comment by Twinkle942910** [comment]
@twyatt Sorry, but is there any solution?(

**Comment by twyatt** [comment]
@Twinkle942910 In your `anim/color_change.xml`, try omitting the `android:valueType="intType"` line?

**Comment by Twinkle942910** [comment]
@twyatt I already tryed, and also added app:vc_valueType="intType", that changed nothing(

**Comment by twyatt** [comment]
Maybe refer to https://github.com/twyatt/vector-compat-test as a starting point? As it was the code I used to test the color implementation.

**Comment by Twinkle942910** [comment]
@twyatt That's doesn't work, I tried(
Here is the screenshot.
image

#And Logs<tag>

```
01-27 23:28:45.369 1091-1091/? W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0xa62d1288)
01-27 23:28:45.373 1091-1091/? E/AndroidRuntime: FATAL EXCEPTION: main
01-27 23:28:45.373 1091-1091/? E/AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.vector_compat_test/com.example.vector_compat_test.MainActivity}: android.content.res.Resources$NotFoundException: File res/drawable/circle_fade.xml from drawable resource ID #0x7f02003c
01-27 23:28:45.373 1091-1091/? E/AndroidRuntime:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2059)
01-27 23:28:45.373 1091-1091/? E/AndroidRuntime:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2084)
01-27 23:28:45.373 1091-1091/? E/AndroidRuntime:     at android.app.ActivityThread.access$600(ActivityThread.java:130)
01-27 23:28:45.373 1091-1091/? E/AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1195)
01-27 23:28:45.373 1091-1091/? E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:99)
01-27 23:28:45.373 1091-1091/? E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:137)
01-27 23:28:45.373 1091-1091/? E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:4745)
01-27 23:28:45.373 1091-1091/? E/AndroidRuntime:     at java.lang.reflect.Method.invokeNative(Native Method)
01-27 23:28:45.373 1091-1091/? E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:511)
01-27 23:28:45.373 1091-1091/? E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
01-27 23:28:45.373 1091-1091/? E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
01-27 23:28:45.373 1091-1091/? E/AndroidRuntime:     at dalvik.system.NativeStart.main(Native Method)
01-27 23:28:45.373 1091-1091/? E/AndroidRuntime:  Caused by: android.content.res.Resources$NotFoundException: File res/drawable/circle_fade.xml from drawable resource ID #0x7f02003c
01-27 23:28:45.373 1091-1091/? E/AndroidRuntime:     at android.content.res.Resources.loadDrawable(Resources.java:1918)
01-27 23:28:45.373 1091-1091/? E/AndroidRuntime:     at android.content.res.Resources.getDrawable(Resources.java:659)
01-27 23:28:45.373 1091-1091/? E/AndroidRuntime:     at com.wnafee.vector.compat.ResourcesCompat.getDrawable(ResourcesCompat.java:34)
01-27 23:28:45.373 1091-1091/? E/AndroidRuntime:     at com.example.vector_compat_test.MainActivity.onCreate(MainActivity.java:22)
01-27 23:28:45.373 1091-1091/? E/AndroidRuntime:     at android.app.Activity.performCreate(Activity.java:5008)
01-27 23:28:45.373 1091-1091/? E/AndroidRuntime:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1079)
01-27 23:28:45.373 1091-1091/? E/AndroidRuntime:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2023)
01-27 23:28:45.373 1091-1091/? E/AndroidRuntime:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2084) 
01-27 23:28:45.373 1091-1091/? E/AndroidRuntime:     at android.app.ActivityThread.access$600(ActivityThread.java:130) 
01-27 23:28:45.373 1091-1091/? E/AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1195) 
01-27 23:28:45.373 1091-1091/? E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:99) 
01-27 23:28:45.373 1091-1091/? E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:137) 
01-27 23:28:45.373 1091-1091/? E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:4745) 
01-27 23:28:45.373 1091-1091/? E/AndroidRuntime:     at java.lang.reflect.Method.invokeNative(Native Method) 
01-27 23:28:45.373 1091-1091/? E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:511) 
01-27 23:28:45.373 1091-1091/? E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786) 
01-27 23:28:45.373 1091-1091/? E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553) 
01-27 23:28:45.373 1091-1091/? E/AndroidRuntime:     at dalvik.system.NativeStart.main(Native Method) 
01-27 23:28:45.373 1091-1091/? E/AndroidRuntime:  Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #2: invalid drawable tag animated-vector
01-27 23:28:45.373 1091-1091/? E/AndroidRuntime:     at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:877)
01-27 23:28:45.373 1091-1091/? E/AndroidRuntime:     at android.graphics.drawable.Drawable.createFromXml(Drawable.java:818)
01-27 23:28:45.373 1091-1091/? E/AndroidRuntime:     at android.content.res.Resources.loadDrawable(Resources.java:1915)
01-27 23:28:45.373 1091-1091/? E/AndroidRuntime:     at android.content.res.Resources.getDrawable(Resources.java:659) 
01-27 23:28:45.373 1091-1091/? E/AndroidRuntime:     at com.wnafee.vector.compat.ResourcesCompat.getDrawable(ResourcesCompat.java:34) 
01-27 23:28:45.373 1091-1091/? E/AndroidRuntime:     at com.example.vector_compat_test.MainActivity.onCreate(MainActivity.java:22) 
01-27 23:28:45.373 1091-1091/? E/AndroidRuntime:     at android.app.Activity.performCreate(Activity.java:5008) 
01-27 23:28:45.373 1091-1091/? E/AndroidRuntime:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1079) 
01-27 23:28:45.373 1091-1091/? E/AndroidRuntime:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2023) 
01-27 23:28:45.373 1091-1091/? E/AndroidRuntime:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2084) 
01-27 23:28:45.373 1091-1091/? E/AndroidRuntime:     at android.app.ActivityThread.access$600(ActivityThread.java:130) 
01-27 23:28:45.373 1091-1091/? E/AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1195) 
01-27 23:28:45.373 1091-1091/? E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:99) 
01-27 23:28:45.373 1091-1091/? E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:137) 
01-27 23:28:45.373 1091-1091/? E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:4745) 
01-27 23:28:45.373 1091-1091/? E/AndroidRuntime:     at java.lang.reflect.Method.invokeNative(Native Method) 
01-27 23:28:45.373 1091-1091/? E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:511) 
01-27 23:28:45.373 1091-1091/? E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786) 
01-27 23:28:45.373 1091-1091/? E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553) 
01-27 23:28:45.373 1091-1091/? E/AndroidRuntime:     at dalvik.system.NativeStart.main(Native Method) 
01-27 23:28:45.373 378-605/? W/ActivityManager:   Force finishing activity com.example.vector_compat_test/.MainActivity
```

**Comment by Twinkle942910** [comment]
@twyatt Maybe you just have to update project on maven? There might be an old version.

**Comment by Twinkle942910** [comment]
@twyatt Are you here?)

**Comment by twyatt** [comment]
@Twinkle942910 This pull request has yet to be accepted, so the changes are not in the version that appears in Maven. You can clone the repo which this pull request comes from and compile it for your project.

**Comment by Twinkle942910** [comment]
@twyatt  Thanks, I'll try

**Comment by twyatt** [comment]
Closing as I imagine people use [`AnimatedVectorDrawableCompat`](https://developer.android.com/reference/androidx/vectordrawable/graphics/drawable/AnimatedVectorDrawableCompat.html) these days.

**Pull request closed without merging**
